################################################################################
# Install Filebeat
################################################################################
- name: Install Filebeat
  apt:
    name: 'filebeat'

- name: Copy beats input
  template:
    src: "templates/filebeat/filebeat.yml"
    dest: "/etc/filebeat/filebeat.yml"
    mode: 0400

- name: Restart Filebeat
  service:
    name: 'filebeat'
    state: 'restarted'
    enabled: yes
